def affichage_pendu(nberreurs):
    if nberreurs == -1:
        print("__________")
        print("|        |")
        print("|")
        print("|")
        print("|")
        print("|")
        print("|")
    if nberreurs == 0:
        print("__________")
        print("|        |")
        print("|")
        print("|")
        print("|")
        print("|")
        print("|")
    if nberreurs == 1:
        print("__________")
        print("|        |")
        print("|        O")
        print("|")
        print("|")
        print("|")
        print("|")
    if nberreurs == 2:
        print("__________")
        print("|        |")
        print("|        O")
        print("|        |")
        print("|        |")
        print("|")
        print("|")
    if nberreurs == 3:
        print("__________")
        print("|        |")
        print("|        O")
        print("|       \|")
        print("|        |")
        print("|")
        print("|")
    if nberreurs == 4:
        print("__________")
        print("|        |")
        print("|        O")
        print("|       \|/")
        print("|        |")
        print("|")
        print("|")
    if nberreurs == 5:
        print("__________")
        print("|        |")
        print("|        O")
        print("|       \|/")
        print("|        |")
        print("|       /")
        print("|")
    if nberreurs == 6:
        print("__________")
        print("|        |")
        print("|        O")
        print("|       \|/")
        print("|        |")
        print("|       / \ ")
        print("|")
